config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
 
  get 'dashboard' => 'home#dashboard', as: :dashboard
  
  devise_for :users

  resources :charges

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :transactions       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    dashboard_path
  end  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  include ChargesHelper	
  before_action :authenticate_user!

  def index
  	@transactions = Transaction.where("user_id=?",current_user.id)
  end

  def new
    @amount = 10    
  end
 
  def create
    # Amount in cents
    Stripe.api_key = get_stripe_settings[Rails.env]["stripe"]["secret_key"]
    amount = 10.to_i * 100

    # Create the customer in Stripe
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
 
    # Create the charge using the customer data returned by Stripe API
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )    
    #add transaction for user.
    Transaction.create({user_id: current_user.id, amount: amount, transaction_number: params[:stripeToken]})
    flash[:notice] = "Payment of $10 is made successfully."
    redirect_to dashboard_path
    # place more code upon successfully creating the charge
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
    flash[:notice] = "Please try again"
  end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #homepage for guest users
  def index
  end

  #Homepage for logged in users
  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
    when :success
      "alert-success"
    when :error
      "alert-error"
    when :alert
      "alert-block"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end

	def root_page_path
		user_signed_in? ? dashboard_path : root_path
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
	def get_stripe_settings
		settings = YAML.load_file("config/stripe_settings.yml")		
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/charges/index.html.erb
<% if @transactions.present? %>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Your Email</th>
      <th>Transaction Date</th>
      <th>Transactio Amount</th>
      <th>Transaction Number</th>
    </tr>
  </thead>
  <tbody>
	    <% @transactions.each_with_index do |transaction, index| %>
	    <tr>
	      <th scope="row"><%= index + 1 %></th>
	      <td><%= transaction.user.email %></td>
	      <td><%= transaction.created_at.strftime("%d-%m-%Y")%></td>
	      <td><%= transaction.amount %></td>
	      <td><%= transaction.transaction_number %></td>
	    </tr>    
	    <% end %>
  </tbody>
</table>
    <% else %>
    	You Have Not Made Transactions Yet. <br/>
    <% end %>
<%= link_to "Back to Dashboard", dashboard_path, class: "btn btn-info"%>

app/views/charges/new.html.erb
<%= form_tag charges_path do -%>
 <article>
     <%= label_tag 'amount', 'To Pay', class: 'amount' %>
     <%= label_tag 'amount', "$#{@amount}.00", class: 'amount-figure' %>
 </article>
 
 <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= get_stripe_settings[Rails.env]["stripe"]["publishable_key"] %>"
    data-description="Sample description for the product."
    data-amount="<%= @amount * 100 %>">
  </script>
<% end %>

app/views/home/dashboard.html.erb
Dashboard for <%= current_user.email %>
<br/>
<a class="btn btn-primary" href="<%= new_charge_path %>" role="button">Make Payment</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StripeTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

<nav role="navigation" class="navbar navbar-inverse">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>         
  </div>

  <!-- Collection of nav links and other content for toggling -->
  <div id="navbarCollapse" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_page_path %>">Home</a></li>
      <% if user_signed_in? %>
        <li><a href="<%= charges_path %>">Transactions</a></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">                               
      <% if user_signed_in? %>
        <li> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
      <% else %>
        <li><%= link_to('Login', new_user_session_path)  %></li>
        <li><%= link_to('Register', new_user_registration_path)  %></li>
      <% end %>
      </li>
    </ul>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-info" %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-info" %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-info" %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "btn btn-info" %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "btn btn-info" %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "btn btn-info" %><br />
  <% end -%>
<% end -%>